liamfoodcorp/acctsys/urls.py
from django.conf.urls import url
from . import views

app_name = 'acctsys'

urlpatterns = [ 
    url(r'^$', views.index, name='index'),
    url(r'^branch/$', views.branch, name='branch'),
    url(r'^coa/$', views.coa, name='coa'),
    url(r'^inventory/$', views.inventory, name='inventory'),
    url(r'^addBranch/$', views.addBranch, name='addBranch'),
    url(r'^addCOA/$', views.addCOA, name='addCOA'),
    url(r'^addProduct/$', views.addProduct, name='addProduct'),

]

liamfoodcorp/liamfoodcorp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('acctsys.urls')),
    url(r'^admin/', admin.site.urls),
]

liamfoodcorp/acctsys/models.py
from django.db import models


class Branch(models.Model):
    branchName = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    defBank = models.CharField(max_length=50)
    
    def __str__(self):
        return self.branchName

    class Meta:
        verbose_name_plural = "Branches"


class ChartOfAccounts(models.Model):
    accGrpentry = models.CharField(max_length=50)
    accCode = models.IntegerField(default=0)
    accDescrip = models.CharField(max_length=50)
    branch = models.ManyToManyField(Branch)
    Debit = 'Debit'
    Credit = 'Credit'
    TYPES_ENTRY =(
        (Debit, 'Debit'),
        (Credit, 'Credit'),
    )
    accEntry = models.CharField(max_length=10, choices=TYPES_ENTRY)
    
    def __str__(self):
        return "ChartAcct - " + str(self.id)

    class Meta:
        verbose_name_plural = "Chart Of Accounts"


class ProductList(models.Model):
    prodCategory = models.CharField(max_length=50) #productList like dimsum, mami, etc.
    
    def __str__(self):
        return self.prodCategory

    class Meta:
        verbose_name_plural = "Product Lists"


class Crew(models.Model):
    crewName = models.CharField(max_length=50)
    
    def __str__(self):
        return self.crewName

    class Meta:
        verbose_name_plural = "Crews"


class Product(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    grpCode = models.CharField(max_length=50)
    prodCode = models.IntegerField(default=0)
    prodDescrip = models.CharField(max_length=50)
    sellingPrice = models.DecimalField(max_digits=20, decimal_places=2)
    purchaseAmt = models.DecimalField(max_digits=20, decimal_places=2)
    actualStock = models.DecimalField(max_digits=20, decimal_places=2)
    
    def __str__(self):
        return str(self.prodCode)

    class Meta:
        verbose_name_plural = "Products"
    

class VoucherInfo(models.Model):
    acctCode = models.IntegerField(default=0)
    acctDescrip = models.CharField(max_length=50)
    debit = models.DecimalField(max_digits=20, decimal_places=2)
    credit = models.DecimalField(max_digits=20, decimal_places=2)

    def __str__(self):
        return "VInfo - " + str(self.id)

    class Meta:
        verbose_name_plural = "Voucher Info"
    

class JV(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    pubDateJV = models.DateTimeField(auto_now_add=True)
    remarks = models.CharField(max_length=150)
    totalAmt = models.DecimalField(max_digits=10, decimal_places=2) #computed fixed amount not editable by user
    vInfo = models.ManyToManyField(VoucherInfo)
    
    def __str__(self):
        return "JV - " + str(self.id)

    class Meta:
        verbose_name_plural = "Journal Vouchers"


class CDV(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    payee = models.CharField(max_length=30)
    checkAmt = models.DecimalField(max_digits=10, decimal_places=2)
    checkNo = models.CharField(max_length=30)
    pubDateCDV = models.DateTimeField(auto_now_add=True)
    remarks = models.CharField(max_length=150)
    totalAmt = models.DecimalField(max_digits=10, decimal_places=2) #computed fixed amount not editable by user
    vInfo = models.ManyToManyField(VoucherInfo)
    
    def __str__(self):
        return "CDV - " + str(self.id)

    class Meta:
        verbose_name_plural = "Cash Disbursement Vouchers"


class CRV(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    receivedFr = models.CharField(max_length=20)
    pubDateCRV = models.DateTimeField(auto_now_add=True)
    remarks = models.CharField(max_length=150)
    totalAmt = models.DecimalField(max_digits=10, decimal_places=2) #computed fixed amount not editable by user
    vInfo = models.ManyToManyField(VoucherInfo)
    
    def __str__(self):
        return "CRV - " + str(self.id)

    class Meta:
        verbose_name_plural = "Cash Receipt Vouchers"


class Sales(models.Model):
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    coa = models.ForeignKey(ChartOfAccounts, on_delete=models.CASCADE)
    crv = models.ForeignKey(CRV, on_delete=models.CASCADE)
    crew = models.ForeignKey(Crew, on_delete=models.CASCADE)
    beginBal = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    incoming = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    availBal = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    out = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    endBal = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    actualCount = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    shortOrOver = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    salesAmt = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    purchaseAmt = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    shortOrOverAmt = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    discount = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    vat = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    netAmt = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    cashOnHand = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    cashInBank = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    remarks = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Sales" + str(self.id)

    class Meta:
        verbose_name_plural = "Sales"

liamfoodcorp/acctsys/forms.py
from django import forms
from django.forms import widgets, ModelChoiceField
from .models import Branch, ChartOfAccounts, Product


class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = [
            'branchName',
            'address',
            'defBank',
        ]
        widgets = {
            'branchName': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter branch name'}),
            'address': forms.TextInput(attrs={'placeholder': 'Enter branch address'}),
            'defBank': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter default bank'}),
            
        }
        
        labels = {
            'branchName': 'Branch Name : ',
            'address': 'Address : ',
            'defBank': 'Default Bank : ',
        }


class COAForm(forms.ModelForm):
    class Meta:
        model = ChartOfAccounts
        exclude = [
            'branch',
        ]
        fields = [
            'accGrpentry', 
            'accCode',
            'accDescrip', 
            'accEntry', 
        ]
        
        widgets = {
            
            'accGrpentry': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter branch name'}),
            'accCode': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter branch name'}),
            'accDescrip': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter account Description'}),
            'accEntry': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter account entry '}),
        }
        
        label = {
            'accGrpentry': 'Account Group Entry', 
            'accCode': 'Account Code',
            'accDescrip': ' Account Description', 
            'accEntry': 'Account Entry (Debit/Credit)',
        }
        
        
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        exclude = [
            'branch',
        ]
        fields = [
            'grpCode',
            'prodCode',
            'prodDescrip', 
            'sellingPrice', 
            'purchaseAmt',
            'actualStock', 
        ]
        widgets = {
            'grpCode': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter grpcode'}),
            'prodCode': forms.NumberInput(attrs={'required': True, 'placeholder': 'Enter prodcode'}),
            'prodDescrip': forms.TextInput(attrs={'required': True, 'placeholder': 'Enter prodDescrip'}),
            'sellingPrice': forms.NumberInput(attrs={'step': 0.01, 'value': '0.00', 'placeholder': '0.00'}),
            'purchaseAmt': forms.NumberInput(attrs={'step': 0.01, 'value': '0.00', 'placeholder': '0.00'}),
            'actualStock': forms.NumberInput(attrs={'step': 0.01, 'value': '0.00', 'placeholder': '0.00'}),
            
        }
        label = {
            'grpCode': 'Group Code : ',
            'prodCode': 'Product Code : ',
            'prodDescrip': 'Product Description : ', 
            'sellingPrice': 'Selling Price : ',
            'purchaseAmt': 'Purchase Amount : ',
            'actualStock': 'Actual Stock : ', 
        }

liamfoodcorp/acctsys/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import ChartOfAccounts, ProductList, Crew, Product, VoucherInfo, JV, CDV, CRV, Branch, Sales
from acctsys.forms import BranchForm, COAForm, ProductForm


def index(request):
    return render(request, 'acctsys/index.html')


def branch(request):
    return render(request, 'acctsys/branch.html')


def coa(request):
    return render(request, 'acctsys/coa.html')


def inventory(request):
    return render(request, 'acctsys/inventory.html')


def addBranch(request):
    if request.method == 'POST':
        branchform = BranchForm(request.POST)
        if branchform.is_valid():
            branchform.save()
            return redirect('/')
    else:
        branchform = BranchForm()
        context = {
            'branchform': branchform
        }
        return render(request, 'acctsys/addbranch.html', context)


def addCOA(request):
    if request.method == 'POST':
        coaform = COAForm(request.POST)
        if coaform.is_valid():
            coaform.save()
            return redirect('/')
    else:
        coaform = COAForm()
        context = {
            'coaform': coaform
        }
        return render(request, 'acctsys/addcoa.html', context)


def addProduct(request):
    # if request.method == 'POST':
    #     productform = ProductForm(request.POST)
    #     if productform.is_valid():
    #         productform.save()
    #         return redirect('/')
    # else:
    productform = ProductForm()
    context = {
        'productform': productform
    }
    return render(request, 'acctsys/addproduct.html', context)

liamfoodcorp/acctsys/templates/acctsys/addbranch.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Branch</title>
</head>
<body>
    add branch page
    {{ branchform.as_p }}
</body>
</html>

liamfoodcorp/acctsys/templates/acctsys/addcoa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add COA</title>
</head>
<body>
    Add coa page
    {{ coaform.as_p }}
</body>
</html>

liamfoodcorp/acctsys/templates/acctsys/addproduct.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add Product</title>
</head>
<body>
    Add product page
    {{ productform.as_p }}
</body>
</html>

liamfoodcorp/acctsys/templates/acctsys/branch.html
<!DOCTYPE html>
<html lang="en">
<head>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">-->
    
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    
    
    <meta charset="UTF-8">
    <title>Branches</title>
</head>
<body>
    
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
          <ul class="nav navbar-nav">
              <li><a href="/">Home</a></li>
              <li class="active"><a href="#">Branch <span class="sr-only">(current)</span></a></li>
          
          
          </ul>
      </div>
    </nav>
    
  <div style="padding: 100px;">
    <div class="panel panel-info">
        <div class="panel-heading">List of Branches
          <a class="btn btn-primary btn-xs" role="button" href="{% url 'acctsys:addBranch' %}">Add branch</a>
        </div>
    <ul class="list-group">
        
      <li class="list-group-item">
          Robinsons Manila 
        <!-- Dropdown button -->
        <div class="btn-group">
          <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
              <li><a href="#">Select</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Edit</a></li>
              <li><a href="#">Delete</a></li>
          </ul>
        </div>
        </li>
        
      <li class="list-group-item">Rob Galle
        <!-- Dropdown button -->
        <div class="btn-group">
          <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
              <li><a href="#">Select</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Edit</a></li>
              <li><a href="#">Delete</a></li>
          </ul>
        </div>
        </li>
    
      <li class="list-group-item">Branch 3
        <!-- Dropdown button -->
        <div class="btn-group">
          <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
              <li><a href="#">Select</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Edit</a></li>
              <li><a href="#">Delete</a></li>
          </ul>
        </div>
        </li>
        
      <li class="list-group-item">Branch 4
        <!-- Dropdown button -->
        <div class="btn-group">
          <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
              <li><a href="#">Select</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Edit</a></li>
              <li><a href="#">Delete</a></li>
          </ul>
        </div>
        </li>
        
      <li class="list-group-item">Branch 5
        <!-- Dropdown button -->
        <div class="btn-group">
          <button class="btn btn-default btn-xs dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More <span class="caret"></span>
          </button>
          <ul class="dropdown-menu">
              <li><a href="#">Select</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Edit</a></li>
              <li><a href="#">Delete</a></li>
          </ul>
        </div>
        </li>
        
        
    </ul>
      
      <br/>
      </div>   
    </div>
    
</body>
</html>

liamfoodcorp/acctsys/templates/acctsys/coa.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Chart of Accounts</title>
</head>
<body>
    <a href="{% url 'acctsys:addCOA' %}">add coa</a>
</body>
</html>

liamfoodcorp/acctsys/templates/acctsys/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Liam Food Corp.</title>
</head>
<body>
    <a href="{% url 'acctsys:branch' %}">branch</a>
    <a href="{% url 'acctsys:coa' %}">coa</a>
    <a href="{% url 'acctsys:inventory' %}">inventory</a>
</body>
</html>

liamfoodcorp/acctsys/templates/acctsys/inventory.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Inventory</title>
</head>
<body>
    <a href="{% url 'acctsys:addProduct' %}">add product</a>
</body>
</html>